### ISSUE TITLE
Index Out of Bounds Exception

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#35]
Today I tested on Windows10, 16 GB RAM
I tried Ac twice and Xs once.
Each test ended with an IndexOutBoundsException after creating all the jpeg and jp2 files for that set, but before closing the Cb and Cr windows (or moving on to the next set).
The first time I had removed the preferences file. The second and third time I left it as it was. 

[INFO] E:\Projects\Ambrosiana_C73inf_062\StaticRaking\Ambrosiana_C73inf_062_Ac_54.jp2
Apr 29, 2018 1:18:36 PM com.slu.imagej.SpectralRTI_Toolkit run
SEVERE: null
java.lang.IndexOutOfBoundsException: Index: 56, Size: 56
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.slu.imagej.SpectralRTI_Toolkit.theMacro_tested(SpectralRTI_Toolkit.java:1004)
	at com.slu.imagej.SpectralRTI_Toolkit.run(SpectralRTI_Toolkit.java:1586)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] Finished processing the run().

**Comment by thehabes** [comment]
This is from the changes around the listOfRakingDirections variable, where the i+1 indexing was.  I will have to investigate that closer.  See #33.
