### ISSUE TITLE
Crash on PCA generate and select 2 (Linux)

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#45]
Tested on Linux, selected PCA and "generate and select 2"
Crashed after running PCA and showing stack and eigenvalue spectrum, before prompting the user to trim the stack to two slices. 
Console as follows:
```
PCA...cleaning eigensystem
May 29, 2018 9:07:07 AM com.slu.imagej.SpectralRTI_Toolkit run
SEVERE: null
java.lang.NullPointerException
	at com.slu.imagej.SpectralRTI_Toolkit.theMacro_tested(SpectralRTI_Toolkit.java:1445)
	at com.slu.imagej.SpectralRTI_Toolkit.run(SpectralRTI_Toolkit.java:1827)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[WARNING] Finished processing the run().
```

**Comment by thehabes** [comment]
Now passing on Windows 7

**Comment by thehabes** [comment]
Now passing on windows 7.

**Comment by thanneken** [comment]
Confirmed on Linux
