### ISSUE TITLE
Crash on Custom (Linux)

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#47]
Crashed with the following output running custom for KTK01
```
[INFO] Should have custom source
[INFO] /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_114/KTK01/Ambrosiana_C73inf_114_KTK_RBbyTX.tif
[INFO] A directory has been created for KTK01 RTI at /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_114/KTK01RTI/
[INFO] Created JP2 /new/JP2file
May 29, 2018 11:40:06 AM com.slu.imagej.SpectralRTI_Toolkit run
SEVERE: null
java.lang.NullPointerException
	at com.slu.imagej.SpectralRTI_Toolkit.theMacro_tested(SpectralRTI_Toolkit.java:1713)
	at com.slu.imagej.SpectralRTI_Toolkit.run(SpectralRTI_Toolkit.java:1827)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[WARNING] Finished processing the run().
```
I'm in St. Louis and have a Linux laptop. Would it make sense for me to come to SLU?

**Comment by thanneken** [comment]
Testing on Windows 10, a slightly different error, before attempting the static raking diffuse:
```
[INFO] Should have custom source
[INFO] F:\Projects\Ambrosiana_C73inf_083\KTK01\Ambrosiana_C73inf_083_KTK_RBbyTX.tif
May 29, 2018 11:57:05 AM com.slu.imagej.SpectralRTI_Toolkit run
SEVERE: null
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.split(String.java:2380)
	at java.lang.String.split(String.java:2422)
	at com.slu.imagej.SpectralRTI_Toolkit.theMacro_tested(SpectralRTI_Toolkit.java:1651)
	at com.slu.imagej.SpectralRTI_Toolkit.run(SpectralRTI_Toolkit.java:1827)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[WARNING] Finished processing the run().
```

**Comment by thehabes** [comment]
Enhanced the logs around this and put in some attempted fixes.

**Comment by thehabes** [comment]
It seems that trying to pull the process name out of the file path was the issue.  I tried to do it with a String like the Macro did, but it was causing these SyntaxErrors.  I am using the File API now instead which is working much better.  

The custom source process should be fixed, I am having successful runs on Windows 7.  I believe this issue still broke it on linux by handing it a file or a path that didn't exist.

**Comment by thehabes** [comment]
Now passing on windows 7, there was an error in the directory naming convention.

**Comment by thanneken** [comment]
Confirmed on Linux
