### ISSUE TITLE
New Crash (Linux)

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#62]
I tried testing on Linux just now. I noticed the latest jar is from May 30, so I probably missed a round of fixes. 

The crash came right after drawing a box for darkest black and whitest non-glare white. 

The console gave:
```
[INFO] Project directory is ...  /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/ ...
[INFO] [preferredFitter=/home/thanneken/wine/HSHfitter/deferredbatch.cmd, preferredCompress=/opt/kakadu/bin/kdu_compress, preferredJp2Args=-rate -,2.4,1.48331273,.91673033,.56657224,.35016049,.21641118,.13374944,.08266171 Creversible=no Clevels=5 Stiles={1024,1024} Cblk={64,64} Cuse_sop=yes Cuse_eph=yes Corder=RPCL ORGgen_plt=yes ORGtparts=R Cmodes=BYPASS -double_buffering 10 -num_threads 4 -no_weights]
[INFO] List of narrow band captures
[INFO] [/media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB365UV_011_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB420VI_001_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB450RB_002_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB470LB_003_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB505CN_004_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB530GN_005_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB560LI_006_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB590AM_007_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB615RO_008_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB630RD_009_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB655DR_010_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB735IR_012_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB850IR_013_F.tif, /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/Captures-Narrowband-NoGamma/Ambrosiana_C73inf_115_MB940IR_014_F.tif]
[INFO] Variable States listed below!
[INFO] lpDesired: false
[INFO] acRtiDesired: true
[INFO] acRakingDesired: true
[INFO] xsRtiDesired: true
[INFO] xsRakingDesired: true
[INFO] psRtiDesired: true
[INFO] psRakingDesired: true
[INFO] csRtiDesired: true
[INFO] csRakingDesired: true
[INFO] webRtiDesired: true
[INFO] shotFileNames: true
[INFO] A directory has been created for lossless static raking images at /media/thanneken/Jub-02/Projects/Ambrosiana_C73inf_115/StaticRaking/
Jun 01, 2018 7:57:42 AM com.slu.imagej.SpectralRTI_Toolkit run
SEVERE: null
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
	at com.slu.imagej.SpectralRTI_Toolkit.theMacro_tested(SpectralRTI_Toolkit.java:451)
	at com.slu.imagej.SpectralRTI_Toolkit.run(SpectralRTI_Toolkit.java:1837)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[WARNING] Finished processing the run().
```

**Comment by thehabes** [comment]
ugh an empty array cannot convert typing.  Have to check existence AND length, if both fail define as an empty array of the type required.  ill test it.

**Comment by thehabes** [comment]
This is fixed, ill put up a new jar shortly.
